# Generated by Django 6.0.2 on 2026-02-09 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReportSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('other', 'Other')], max_length=10)),
                ('animal_count', models.PositiveIntegerField(default=1)),
                ('manual_location', models.CharField(help_text='Road name and nearby landmark', max_length=255)),
                ('auto_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('auto_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_source', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automatic'), ('mixed', 'Manual + Automatic')], default='manual', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conditions', models.ManyToManyField(blank=True, to='App.condition')),
            ],
        ),
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stray_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='App.reportsubmit')),
            ],
        ),
    ]
