# Generated by Django 5.2.5 on 2026-02-22 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(help_text='e.g., 2 years, 6 months', max_length=50)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('story', models.TextField()),
                ('health_status', models.TextField(help_text='Vaccination and medical history')),
                ('image', models.ImageField(blank=True, null=True, upload_to='animals/')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Adopted', 'Adopted')], default='Available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('applicant_phone', models.CharField(max_length=20)),
                ('home_environment', models.TextField(help_text='Describe your home, work hours, lifestyle.')),
                ('status', models.CharField(choices=[('Waiting', 'Waiting for Reply'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Waiting', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='App.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='App.animal')),
            ],
        ),
    ]
