# Generated by Django 6.0.2 on 2026-02-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsubmit',
            name='location_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('gps', 'GPS')], default='manual', max_length=10),
        ),
    ]
