# Generated by Django 6.0.2 on 2026-02-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_reportsubmit_location_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportsubmit',
            name='description',
        ),
    ]
