# Generated by Django 5.2.5 on 2026-02-22 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_animal_adoptionapplication_sponsorship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportsubmit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reportsubmit',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='reportsubmit',
            name='user',
        ),
        migrations.AddField(
            model_name='reportsubmit',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportsubmit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('rescued', 'Rescued')], default='pending', max_length=20),
        ),
    ]
