# Generated by Django 5.2.5 on 2026-02-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_reportsubmit_claimed_at_reportsubmit_reporter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('On Process', 'On process of adoption'), ('Adopted', 'Adopted')], default='Available', max_length=20),
        ),
    ]
