# Generated by Django 5.2.5 on 2026-02-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_animal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='in_adoption',
            field=models.BooleanField(default=False),
        ),
    ]
