# Generated by Django 5.2.5 on 2026-02-23 04:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_animal_in_adoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsubmit',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
