# Generated by Django 5.2.5 on 2026-02-23 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_reportsubmit_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_profile', to='App.reportsubmit'),
        ),
    ]
