# Generated by Django 5.2.5 on 2026-03-01 15:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_animal_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='panchayat',
        ),
        migrations.AddField(
            model_name='profile',
            name='local_body',
            field=models.CharField(default=django.utils.timezone.now, help_text='Name of the Panchayat or Municipality', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(help_text='Full house address/landmark'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='house_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ward_no',
            field=models.CharField(max_length=10),
        ),
    ]
