# Generated by Django 5.2.5 on 2026-03-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_remove_profile_municipality_remove_profile_panchayat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='center_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='center_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='center_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='center_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='center_type',
            field=models.CharField(blank=True, choices=[('ngo', 'NGO'), ('government', 'Govt Shelter'), ('foster', 'Foster')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=1501),
        ),
    ]
