# Generated by Django 5.2.5 on 2026-03-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_animal_center_address_animal_center_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionapplication',
            name='current_pet_type',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='env_quality',
            field=models.CharField(default='good', max_length=50),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='has_pet',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='home_ownership',
            field=models.CharField(default='owned', max_length=50),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='income_amount',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='income_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='is_18',
            field=models.CharField(default='yes', max_length=5),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='landlord_permission',
            field=models.CharField(default='not_applicable', max_length=50),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='residence_type',
            field=models.CharField(default='house', max_length=50),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='stable_income',
            field=models.CharField(default='yes', max_length=5),
        ),
    ]
