# Generated by Django 5.2.5 on 2026-03-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_adoptionapplication_current_pet_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionapplication',
            name='amenities',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
