# Generated by Django 5.2.5 on 2026-03-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_adoptionapplication_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsubmit',
            name='is_verified_rescue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportsubmit',
            name='rescue_image',
            field=models.ImageField(blank=True, help_text='Live photo of the animal at the center or safe-zone', null=True, upload_to='rescue_proof/'),
        ),
        migrations.AddField(
            model_name='reportsubmit',
            name='rescue_notes',
            field=models.TextField(blank=True, help_text="Details about the animal's current location and condition", null=True),
        ),
        migrations.AddField(
            model_name='reportsubmit',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
