# Generated by Django 5.2.5 on 2026-03-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_reportsubmit_is_verified_rescue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsubmit',
            name='rescue_image',
            field=models.ImageField(blank=True, null=True, upload_to='rescue_proof/'),
        ),
    ]
