# Generated by Django 5.2.5 on 2026-03-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_alter_reportsubmit_rescue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_volunteer',
            field=models.BooleanField(default=False),
        ),
    ]
