# Generated by Django 5.2.5 on 2026-03-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_profile_is_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_volunteer_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
    ]
