# Generated by Django 5.2.5 on 2026-03-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_profile_is_volunteer_pending_alter_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionapplication',
            name='is_submitted_for_final_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='proof_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='adoption_proof/'),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='proof_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='adoption_proof/'),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='user_notes',
            field=models.TextField(blank=True, help_text='Tell us how the animal is settling in!', null=True),
        ),
        migrations.AlterField(
            model_name='reportsubmit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('awaiting_verification', 'Awaiting Verification'), ('rescued', 'Rescued')], default='pending', max_length=30),
        ),
    ]
