# Generated by Django 5.2.5 on 2026-03-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_adoptionapplication_is_submitted_for_final_verify_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionapplication',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting for Reply'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Proof_Submitted', 'Proof Submitted'), ('Verified', 'Verified')], default='Waiting', max_length=20),
        ),
    ]
