# Generated by Django 5.2.5 on 2026-03-07 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_adoptionapplication_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionapplication',
            name='user',
        ),
    ]
