# Generated by Django 5.2.5 on 2026-03-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_remove_adoptionapplication_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionapplication',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting for Reply'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Proof_Submitted', 'Proof Submitted'), ('Verified', 'Verified'), ('Adopted', 'Adopted')], default='Waiting', max_length=20),
        ),
    ]
