# Generated by Django 5.2.5 on 2026-03-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_alter_adoptionapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionapplication',
            name='income_amount',
        ),
        migrations.RemoveField(
            model_name='adoptionapplication',
            name='income_source',
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting for Reply'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Proof_Submitted', 'Proof Submitted'), ('Verified', 'Verified')], default='Waiting', max_length=20),
        ),
    ]
