# Generated by Django 5.2.5 on 2026-03-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_remove_adoptionapplication_income_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Thrissur', max_length=100),
        ),
    ]
