# Generated by Django 5.2.5 on 2026-03-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='local_body',
            field=models.CharField(default='', help_text='Name of the Panchayat or Municipality', max_length=100),
        ),
    ]
