# Generated by Django 5.2.5 on 2026-03-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_alter_profile_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('org_type', models.CharField(choices=[('ngo', 'NGO'), ('vet', 'Veterinary Clinic'), ('adoption', 'Adoption Center')], max_length=20)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('local_body', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('registration_number', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='organizations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
