# Generated by Django 5.2.5 on 2026-03-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
